services:
  nginx:
    image: nginx:latest
    container_name: my_nginx_container
    restart: unless-stopped
    ports:
      - "80:80" # Map host port 80 to container port 80
    volumes:
      - ./html:/usr/share/nginx/html:ro # Mount local 'html' directory to Nginx's default web root
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount a custom Nginx configuration file